# Setup
title: d5n5 Universal Apps
url: https://d5n5.com
email: contact@d5n5.com
# paginate: 1
# paginate_path: "/page:num/"
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  # - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jo Sprague
  url: https://josprague.com/
  email: josprague@d5n5.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:

  - title: Services
    url: /services

  - title: Portfolio
    url: /portfolio

  - title: Work With Us
    url: /contact
